export const metadata = {
  title: 'Blog Summarizer',
  // description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style>{`
          body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: linear-gradient(135deg, #c3ecf9, #a6c1ee);
            font-family: Arial, sans-serif;
          }

          .content-box {
            background: white;
            padding: 2rem 3rem;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 90%;
          }
        `}</style>
      </head>
      <body>
        <div className="content-box">
          {children}
        </div>
      </body>
    </html>
  )
}
